name: Test artifacts

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch to run the workflow on"
        required: true
        default: "master"

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Building release application
        run: |
          make release
      - name: Building unit tests
        run: |
          cd tests/unit
          make all
      - name: Doing unit test scenarios
        run: |
          cd tests/unit
          ./bin/test_lexer
          ./bin/test_parser
          ./bin/test_compiler
          ./bin/test_builder
      - name: Doing integration test scenarios
        run: |
          make release
          cd tests/integration
          ./test.sh
