name: Test artifacts

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch to run the workflow on"
        required: true
        default: "master"

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Building release application
        run: |
          make release
      - name: Doing unit test scenarios
        run: |
          make test-unit
      - name: Doing integration test scenarios
        run: |
          make test-integration
